name: ON PR SYNC
on: 
  pull_request:
    types: [opened, synchronize, reopened, labeled, closed]

jobs:
  job-zero:
    name: job-check
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.should-deploy.outputs.result }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          ref: 'test-action'
      - id: should-deploy
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const script = require('./betaDeploy.js')
            const result = await script({github, context, exec});
            return result;
      - id: set-output
        run: echo "result=${{steps.should-deploy.outputs.result}}" >> $GITHUB_OUTPUT
  job-one:
    runs-on: ubuntu-latest
    needs: [job-zero]
    if: ${{ needs.job-zero.outputs.result == 'true' }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          ref: 'test-action'
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Get result
        run: echo "${{steps.beta-deploy.outputs.result}}"

