name: ON PR SYNC
on: 
  pull_request:
    types: [opened, synchronize, reopened, labeled, closed]

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          ref: 'test-action'
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Check If Any PR contains Beta tag
        id: beta-deploy
        uses: actions/github-script@v6
        with:
          result-encoding: boolean
          script: |
            const script = require('./betaDeploy.js')
            const result=await script({github, context, exec});
            return result;
      - name: Get result
        run: echo "${{steps.beta-deploy.outputs.result}}"

