name: ON PR SYNC
on: 
  pull_request:
    types: [opened, synchronize, reopened, labeled, closed]

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Check If Any PR contains Beta tag
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./betaDeploy.js')
            await script({github, context, exec})

